version: '3'
services:
    mongodb:
        image: mongo
        container_name: kong-mongodb
        volumes:
            - ../deployment/kong/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    # redis:
    #     image: redis
    #     container_name: kong-redis
    #     restart: always
    #     networks:
    #         - default
    #     logging:
    #         options:
    #             max-size: "10m"
    #             max-file: "3"
    web:
        build: .
        image: kong-image
        container_name: kong-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9000:9000
        links:
            - mongodb
        networks:
            - default
        restart: always
        environment:
            KONG_SETTINGS: /app/kong-production.cfg
        command:
          /venv/bin/gunicorn -w 2 --bind 0.0.0.0:9000 "kong.web:create_app()"
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    # worker:
    #     build: .
    #     image: kong-image
    #     container_name: kong-worker
    #     volumes:
    #         - ../deployment:/deployment
    #         - /etc/localtime:/etc/localtime:ro
    #     depends_on:
    #         - mongodb
    #         - redis
    #     links:
    #         - mongodb
    #         - redis
    #     restart: always
    #     environment:
    #         KONG_SETTINGS: /app/kong-production.cfg
    #     command:
    #         /venv/bin/kong-worker
    #     logging:
    #         options:
    #             max-size: "10m"
    #             max-file: "3"

networks:
    default:
